### ISSUE TITLE
Add support for simplified Chinese

### ISSUE THREAD

**Issue by wildplant** [caleb531/youversion-suggest#2]
Thank you , may GOD bless you!

how can I add a new language support, such as chinese?

**Comment by caleb531** [comment]
I would need to add support for the language on your behalf. However, note that I am only able to add support for languages which the YouVersion Bible supports. I'm assuming that Chinese is the language in question here, and so because I am not as familiar with the language, I would like to work with you to add support in a way that would make sense to you.

If you could please look through [this list](https://www.bible.com/versions) and tell me the particular supported language (from the list) that would work for you, I can begin working on adding it.

**Comment by wildplant** [comment]
https://www.bible.com/zh-CN/versions/48-cunpss-xin-biao-dian-he-he-ben-shen-ban

CUNPSS  is the most popular version in Chinese christians. That is what I need. Thanks.

**Comment by wildplant** [comment]
if you need me edit some language json file, please let me know.

**Comment by caleb531** [comment]
Thanks, @wildplant, however there *should* be no need for that. I've just submitted a pull request with my additions for simplified Chinese (zh-CN). Please see issue #4 and let me know if any changes need to be made. :)

Caleb

**Comment by wildplant** [comment]
![yv-zh](https://cloud.githubusercontent.com/assets/2607493/7266213/adcc135c-e8d8-11e4-9987-d0bec8b7e9fa.png)

I copied the 2 files to my workflow folder, it works. thank you.

**Comment by caleb531** [comment]
Great, though I was still planning on updating the packaged workflow with the new language support.

Please download/install the packaged workflow on `develop` and let me know if everything still works.

Thanks,
Caleb
