### ISSUE TITLE
Copy verse to clipboard 

### ISSUE THREAD

**Issue by wildplant** [caleb531/youversion-suggest#3]
I hope this feature will be considered:

1.   type yv john 3:16;
2.   the verse display below
3.   select the verse the press enter
4.   the verse was copied to clipboard

**Comment by caleb531** [comment]
I added this feature a while back, however I ultimately decided to remove it because the implementation was complicated and the behavior wasn't very consistent.

**Comment by caleb531** [comment]
Hi, @wildplant. I'm reopening this issue because, well, I actually plan on adding "copy to clipboard" functionality to YouVersion Suggest.

I know, I know—I said I wouldn't—but I've been able to hammer out the necessary logic to creating a parser that will accurately fetch and format any chapter, verse, or range of verses from the YouVersion website. It's very awesome. :)

I will be officially releasing this soon—I just thought you might like to know. :)
